name: main

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Delete old prerelease
        if: github.ref_type == 'branch'
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version for tag
        if: github.ref_type == 'tag'
        run: echo "version=$(git describe --tags --match 'v*')" >> $GITHUB_ENV

      - name: Set version for branch
        if: github.ref_type == 'branch'
        run: echo "version=$(git describe --tags)" >> $GITHUB_ENV

      - name: Test
        run: |
          xcodebuild test -project TomatoBar.xcodeproj -scheme TomatoBar \
            -destination 'platform=macOS' CODE_SIGNING_ALLOWED=NO

      - name: Build
        run: |
          BUILT_PRODUCTS_DIR=$(xcodebuild -project TomatoBar.xcodeproj -scheme TomatoBar -configuration Release -showBuildSettings | awk '/^ *BUILT_PRODUCTS_DIR = / {print $3}')
          xcodebuild build -project TomatoBar.xcodeproj -scheme TomatoBar \
            -configuration Release CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO
          cp -r "$BUILT_PRODUCTS_DIR/TomaTrace.app" .
          ditto -c -k --keepParent "TomaTrace.app" "TomaTrace-${{env.version}}.zip"

      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: TomaTrace-${{env.version}}.zip

      - name: Prerelease
        if: github.ref_type == 'branch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: prerelease
          prerelease: true
          files: TomaTrace-${{env.version}}.zip
